In [5]:
import requests

In [35]:
BASE_URL = "https://api.semanticscholar.org/graph/v1/paper/search/bulk"

def search_papers(
    query=None,
    venue=None,
    fields_of_study=None,
    publication_types=None,
    date_range=None,
    sort="publicationDate",
    # limit=100,
    # offset=0
):
    params = {
        "fields": "paperId,title,year,abstract,venue,publicationDate",
        "sort": sort
        # ,
        # "limit": limit,
        # "offset": offset
    }

    if query:
        params["query"] = query

    if venue:
        params["venue"] = venue

    if fields_of_study:
        params["fieldsOfStudy"] = fields_of_study

    if publication_types:
        params["publicationTypes"] = publication_types

    if date_range:
        params["publicationDateOrYear"] = date_range

    response = requests.get(BASE_URL, params=params)

    if response.status_code != 200:
        raise Exception(f"Error {response.status_code}: {response.text}")

    return response.json()

In [36]:
result = search_papers(
    venue="Transactions of the Association for Computational Linguistics",
    fields_of_study="Computer Science",
    publication_types="JournalArticle",
    date_range="2010-03-05:2025-06-06"
)

print("Total papers:", result.get("total", 0))
print("First paper:")
print(result["data"][0])

Total papers: 819
First paper:
{'paperId': 'cd0a1d660771c9d2fa42c9446fbc1f441d40e9d1', 'title': 'A Novel Feature-based Bayesian Model for Query Focused Multi-document Summarization', 'venue': 'Transactions of the Association for Computational Linguistics', 'year': 2012, 'openAccessPdf': {'url': 'http://www.mitpressjournals.org/doi/pdf/10.1162/tacl_a_00212', 'status': 'GOLD', 'license': 'CCBY', 'disclaimer': 'Notice: Paper or abstract available at https://arxiv.org/abs/1212.2006, which is subject to the license by the author or copyright owner provided with this content. Please go to the source to verify the license and copyright information for your use.'}, 'publicationDate': '2012-12-10', 'authors': [{'authorId': '2386020789', 'name': 'Jiwei Li'}, {'authorId': '1695451', 'name': 'Sujian Li'}], 'abstract': 'Supervised learning methods and LDA based topic model have been successfully applied in the field of multi-document summarization. In this paper, we propose a novel supervised approach that can incorporate rich sentence features into Bayesian topic models in a principled way, thus taking advantages of both topic model and feature based supervised learning methods. Experimental results on DUC2007, TAC2008 and TAC2009 demonstrate the effectiveness of our approach.'}

In [37]:
import pandas as pd

In [38]:
papers = result["data"]

df = pd.DataFrame(papers)
df

,paperId,title,venue,year,openAccessPdf,publicationDate,authors,abstract
0,cd0a1d660771c9d2fa42c9446fbc1f441d40e9d1,A Novel Feature-based Bayesian Model for Query...,Transactions of the Association for Computatio...,2012,{'url': 'http://www.mitpressjournals.org/doi/p...,2012-12-10,"[{'authorId': '2386020789', 'name': 'Jiwei Li'...",Supervised learning methods and LDA based topi...
1,2ae77bb984dce5af3181a28340d603ad9bb0b9b1,Extensions of Ordering Sets of States from Eff...,Transactions of the Association for Computatio...,2013,{'url': 'https://easychair.org/publications/op...,2013-02-24,"[{'authorId': '102679761', 'name': 'Ji R I Jan...",None
2,03c605c8b0bdd7ce7e2123ab6394dcc25f70f6a9,Finding Optimal 1-Endpoint-Crossing Trees,Transactions of the Association for Computatio...,2013,{'url': 'http://www.mitpressjournals.org/doi/p...,2013-03-01,"[{'authorId': '2585932', 'name': 'Emily Pitler...",Dependency parsing algorithms capable of produ...
3,21b3007f967d39e1346bc91e0fc8b3f16121300c,Grounding Action Descriptions in Videos,Transactions of the Association for Computatio...,2013,{'url': 'http://www.mitpressjournals.org/doi/p...,2013-03-31,"[{'authorId': '2485529', 'name': 'Michaela Reg...",Recent work has shown that the integration of ...
4,22566980b49e2b2d3594f9446f7398da5d344a5c,Branch and Bound Algorithm for Dependency Pars...,Transactions of the Association for Computatio...,2013,{'url': 'http://www.mitpressjournals.org/doi/p...,2013-03-31,"[{'authorId': '2067733840', 'name': 'Xian Qian...",Graph based dependency parsing is inefficient ...
...,...,...,...,...,...,...,...,...
814,4a7edb588d5a64ddba51c1c792154e2a68ea3b96,Evaluating Visual Representations for Topic Un...,Transactions of the Association for Computatio...,2017,"{'url': '', 'status': None, 'license': None}",None,"[{'authorId': '2341389585', 'name': 'Alison Sm...",None
815,8c0a9baccd0dd81c0212e102d2f5c508118e9342,Morphological analysis using a sequence decoder,Transactions of the Association for Computatio...,2019,{'url': 'https://direct.mit.edu/tacl/article-p...,None,"[{'authorId': '46185703', 'name': 'Erenay Daya...","We introduce Morse, a recurrent encoder-decode..."
816,d0960dab84785ad826cb6a2bafb087d7f9347c5d,Trick Me If You Can: Human-in-the-loop Generat...,Transactions of the Association for Computatio...,2019,"{'url': '', 'status': None, 'license': None}",None,"[{'authorId': '2056825758', 'name': 'Eric Wall...",None
817,078065b62af527fa6cbd83bcdc58ee59e7678e23,Federated Learning for Exploiting Annotators’ ...,Transactions of the Association for Computatio...,2024,{'url': 'https://direct.mit.edu/tacl/article-p...,None,"[{'authorId': '51303384', 'name': 'Nuria Rodrí...",The annotation of ambiguous or subjective NLP ...
818,1f3a9771bdcbdbcbbc0249bd0f96c5baa8ac6fae,Computational Complexity of Natural Morphology...,Transactions of the Association for Computatio...,2024,{'url': 'https://direct.mit.edu/tacl/article-p...,None,"[{'authorId': '3167945', 'name': 'Hajime Senum...","This paper revisits a classical, yet fundament..."

In [39]:
df["publicationDate"] = pd.to_datetime(df["publicationDate"])
df["month"] = df["publicationDate"].dt.month
df[["publicationDate", "month"]].head()
df["publicationDate"] = pd.to_datetime(
    df["publicationDate"],
    errors="coerce"
)
df["month"] = df["publicationDate"].dt.month.fillna(1).astype(int)
df["four_month_section"] = ((df["month"] - 1) // 4 + 1).astype(int)

In [40]:
df

,paperId,title,venue,year,openAccessPdf,publicationDate,authors,abstract,month,four_month_section
0,cd0a1d660771c9d2fa42c9446fbc1f441d40e9d1,A Novel Feature-based Bayesian Model for Query...,Transactions of the Association for Computatio...,2012,{'url': 'http://www.mitpressjournals.org/doi/p...,2012-12-10,"[{'authorId': '2386020789', 'name': 'Jiwei Li'...",Supervised learning methods and LDA based topi...,12,3
1,2ae77bb984dce5af3181a28340d603ad9bb0b9b1,Extensions of Ordering Sets of States from Eff...,Transactions of the Association for Computatio...,2013,{'url': 'https://easychair.org/publications/op...,2013-02-24,"[{'authorId': '102679761', 'name': 'Ji R I Jan...",None,2,1
2,03c605c8b0bdd7ce7e2123ab6394dcc25f70f6a9,Finding Optimal 1-Endpoint-Crossing Trees,Transactions of the Association for Computatio...,2013,{'url': 'http://www.mitpressjournals.org/doi/p...,2013-03-01,"[{'authorId': '2585932', 'name': 'Emily Pitler...",Dependency parsing algorithms capable of produ...,3,1
3,21b3007f967d39e1346bc91e0fc8b3f16121300c,Grounding Action Descriptions in Videos,Transactions of the Association for Computatio...,2013,{'url': 'http://www.mitpressjournals.org/doi/p...,2013-03-31,"[{'authorId': '2485529', 'name': 'Michaela Reg...",Recent work has shown that the integration of ...,3,1
4,22566980b49e2b2d3594f9446f7398da5d344a5c,Branch and Bound Algorithm for Dependency Pars...,Transactions of the Association for Computatio...,2013,{'url': 'http://www.mitpressjournals.org/doi/p...,2013-03-31,"[{'authorId': '2067733840', 'name': 'Xian Qian...",Graph based dependency parsing is inefficient ...,3,1
...,...,...,...,...,...,...,...,...,...,...
814,4a7edb588d5a64ddba51c1c792154e2a68ea3b96,Evaluating Visual Representations for Topic Un...,Transactions of the Association for Computatio...,2017,"{'url': '', 'status': None, 'license': None}",NaT,"[{'authorId': '2341389585', 'name': 'Alison Sm...",None,1,1
815,8c0a9baccd0dd81c0212e102d2f5c508118e9342,Morphological analysis using a sequence decoder,Transactions of the Association for Computatio...,2019,{'url': 'https://direct.mit.edu/tacl/article-p...,NaT,"[{'authorId': '46185703', 'name': 'Erenay Daya...","We introduce Morse, a recurrent encoder-decode...",1,1
816,d0960dab84785ad826cb6a2bafb087d7f9347c5d,Trick Me If You Can: Human-in-the-loop Generat...,Transactions of the Association for Computatio...,2019,"{'url': '', 'status': None, 'license': None}",NaT,"[{'authorId': '2056825758', 'name': 'Eric Wall...",None,1,1
817,078065b62af527fa6cbd83bcdc58ee59e7678e23,Federated Learning for Exploiting Annotators’ ...,Transactions of the Association for Computatio...,2024,{'url': 'https://direct.mit.edu/tacl/article-p...,NaT,"[{'authorId': '51303384', 'name': 'Nuria Rodrí...",The annotation of ambiguous or subjective NLP ...,1,1
818,1f3a9771bdcbdbcbbc0249bd0f96c5baa8ac6fae,Computational Complexity of Natural Morphology...,Transactions of the Association for Computatio...,2024,{'url': 'https://direct.mit.edu/tacl/article-p...,NaT,"[{'authorId': '3167945', 'name': 'Hajime Senum...","This paper revisits a classical, yet fundament...",1,1